<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1514098304874' stop='1514098312422'>
    <name>Bank Manager Login Test</name>
    <title>Bank Manager Login Test</title>
    <test-cases>
        <test-case start='1514098304874' status='passed' stop='1514098311351'>
            <name>should login as bank manager</name>
            <title>should login as bank manager</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='ddf6cd8c-1dca-4c52-88cb-bf698d04d3a5-attachment.png' type='image/png' size='37626'/>
            </attachments>
        </test-case>
        <test-case start='1514098311351' status='failed' stop='1514098312421'>
            <name>should add a customer</name>
            <title>should add a customer</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>UnexpectedAlertOpenError: unexpected alert open: {Alert text : Customer added successfully with customer id :6}
                  (Session info: chrome=63.0.3239.84)
                  (Driver info: chromedriver=2.34.522932 (4140ab217e1ca1bec0c4b4d1b148f3361eb3a03e),platform=Mac OS X 10.13.2 x86_64)</message>
                <stack-trace>UnexpectedAlertOpenError: unexpected alert open: {Alert text : Customer added successfully with customer id :6}
                  (Session info: chrome=63.0.3239.84)
                  (Driver info: chromedriver=2.34.522932 (4140ab217e1ca1bec0c4b4d1b148f3361eb3a03e),platform=Mac OS X 10.13.2 x86_64)
                    at Object.checkLegacyResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:553:13)
                    at parseHttpResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
                    at doSend.then.response (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:441:30)
                    at &lt;anonymous>
                    at process._tickCallback (internal/process/next_tick.js:188:7)
                From: Task: WebDriver.takeScreenshot()
                    at Driver.schedule (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
                    at Driver.takeScreenshot (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:1085:17)
                    at run (/usr/local/lib/node_modules/protractor/built/browser.js:59:33)
                    at ProtractorBrowser.to.(anonymous function) [as takeScreenshot] (/usr/local/lib/node_modules/protractor/built/browser.js:67:16)
                    at UserContext.&lt;anonymous> (/Users/suyashnande/WebstormProjects/BankPageObjects/configuration/conf.js:29:21)
                    at attempt (/usr/local/lib/node_modules/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4297:26)
                    at QueueRunner.run (/usr/local/lib/node_modules/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4217:20)
                    at runNext (/usr/local/lib/node_modules/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4257:20)
                    at /usr/local/lib/node_modules/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4264:13
                    at /usr/local/lib/node_modules/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4172:9</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>